// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "obsidianTagName": string;
      "hotkeyCreateLitNote": string;
      "hotkeySyncTags": string;
      "hotkeyToggleLeftPane": string;
      "hotkeyToggleRightPane": string;
      "hotkeyOpenLitNote": string;
    };
  }
}
